### ISSUE TITLE
I'd like to contribute

### ISSUE THREAD

**Issue by GrantorShadow** [karanchahal/papers#2]
Hi Karan,
I have been following your GitHub account from a while and have been delving deep into ML & DL. As per mentioned, you are accepting contributions to your Repo "papers". I would also like to submit my notes on the papers which I am currently reading.
I would like to ask you for permission for the same.

Thanks,
Shaunak

**Comment by karanchahal** [comment]
Yeah sure :) You're more than welcome to. 
What papers are you reading currently?

**Comment by GrantorShadow** [comment]
Appreciate your answer!
I was reading some papers on basics such as ZF-Net, VGG & ResNet and some fairly advanced ones SSD/ YOLO and Mask R-CNN. I notice that you have not covered Mask R-CNN. Would be a good contribution? I shall be starting my reading on human pose representation and its applications, I suppose they shall be a good read to add here.

Thanks

**Comment by karanchahal** [comment]
Actually all the object detection algorithms have been added. You can check the file name object_recognition.md for details. I'd really love it if you can write some material on human pose representation though !

**Comment by GrantorShadow** [comment]
Yes, that sounds great!
I'll create a pull request ASAP when I finish with my notes. Might take a while.

Thanks
